### ISSUE TITLE
json_module as submodule or dependency

### ISSUE THREAD

**Issue by RussTorres** [fcollman/render-python-apps#2]
Multiple json_module implementations are being tracked and updated with different commits.  This will complicate dependency management for forking (or branching) development.  It would help to have a public git repo that shares commit history with the finalized version of json_module.

**Comment by fcollman** [comment]
Yes, i'm submitted json_module to be released seperately, and hope to take it out of render-python-apps as soon as that happens, and then it will simply be a dependancy.  I agree its presently not ideal.
